name: DeployToAWS

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkouts@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.4.1

            - name: Npm install & npm build
              run: |
                npm install
                npm run build

            - name: S3 Sync
              uses: jakejarvis/s3-sync-action@v0.5.1

              env:
                  AWS_S3_BUCKET: 'mygitdemobucket'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: 'us-east-1'
                  SOURCE_DIR: 'dist/ng-fundamentals'
